"use client";

import { createContext, useContext, useEffect, useState } from "react";

type Language = "es" | "en";

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  es: {
    "app.brand": "STYLEHUB",
    "app.subtitle.client": "Mi cuenta",
    "app.subtitle.business": "Panel Negocio",
    "nav.dashboard": "Dashboard",
    "nav.dashboard.client": "Resumen",
    "nav.dashboard.business": "Resumen",
    "nav.salons": "Salones",
    "nav.appointments": "Mis citas",
    "nav.payments": "Pagos",
    "nav.settings": "Ajustes",
    "nav.branches": "Sucursales",
    "nav.services": "Servicios",
    "nav.stylists": "Estilistas",
    "nav.profile": "Perfil",
    "nav.home": "Inicio",
    "nav.logout": "Salir",
    "tip.client.title": "Consejo",
    "tip.client.body": "Agenda con anticipación y guarda una tarjeta para checkout rápido.",
    "tip.business.title": "Tip negocio",
    "tip.business.body": "Mantén tus servicios y estilistas actualizados para convertir más reservas.",
    "dashboard.client.welcome": "¡Bienvenido de vuelta! 👋",
    "dashboard.client.subtitle": "Aquí tienes un resumen de tu actividad y próximas citas.",
    "dashboard.client.totalAppointments": "Citas totales",
    "dashboard.client.pending": "Pendientes",
    "dashboard.client.confirmed": "Confirmadas",
    "dashboard.client.methods": "Métodos",
    "dashboard.client.spent": "Gastado",
    "dashboard.client.upcoming": "Próximas citas",
    "dashboard.client.agenda": "Tu agenda",
    "dashboard.client.activity": "Actividad",
    "dashboard.client.latest": "Últimas reservas",
    "dashboard.client.activeMethod": "Método activo",
    "dashboard.client.fastPay": "Pago rápido",
    "dashboard.client.savedMethods": "Métodos guardados",
    "dashboard.client.methodsActive": "Tienes opciones de pago activas.",
    "dashboard.client.steps": "Próximos pasos",
    "dashboard.client.step1": "Agenda tu primera cita",
    "dashboard.client.step2": "Guarda un método de pago",
    "dashboard.client.step3": "Recibe confirmaciones por email",
    "dashboard.client.noUpcoming": "Sin citas próximas",
    "dashboard.client.noUpcomingDesc": "Agenda una cita para ver tu calendario.",
    "dashboard.client.methodType": "Tipo",
    "dashboard.client.noMethod": "Sin método configurado",
    "dashboard.client.noMethodDesc": "Agrega un método para checkout más rápido.",
    "dashboard.business.title": "Control total de tu salón",
    "dashboard.business.subtitle": "Gestiona servicios, equipo y citas desde un solo lugar.",
    "dashboard.business.quickActions": "Acciones rápidas",
    "dashboard.business.manageServices": "Administrar servicios",
    "dashboard.business.manageStylists": "Gestionar estilistas",
    "dashboard.business.reviewAppointments": "Revisar citas",
    "dashboard.business.manageBranches": "Gestionar sucursales",
    "dashboard.business.configureSalon": "Configurar salón",
    "dashboard.business.monthlyPerformance": "Rendimiento mensual",
    "dashboard.business.revenue": "Ingresos confirmados por servicios completados este mes.",
    "dashboard.business.services": "Servicios",
    "dashboard.business.stylists": "Estilistas",
    "dashboard.business.branches": "Sucursales",
    "dashboard.business.upcoming": "Citas próximas",
    "dashboard.business.clients": "Clientes",
    "dashboard.business.revenueMonth": "Ingresos mes",
    "dashboard.business.summary": "Dashboard Negocio",
    "dashboard.business.control": "Gestiona servicios, equipo y citas desde un solo lugar.",
    "salons.badge": "Premium Beauty Network",
    "salons.title": "Descubre nuestros salones 💇",
    "salons.subtitle": "Explora salones verificados, compara servicios y agenda con estilistas expertos en segundos.",
    "salons.available": "salones disponibles",
    "salons.favorites": "Tus favoritos ❤️",
    "salons.saved": "guardados",
    "salons.noAvailable": "No hay salones disponibles",
    "salons.noAvailableDesc": "Vuelve más tarde para ver nuevas opciones de reserva.",
    "salons.verified": "Verificado",
    "salons.viewServices": "Ver servicios",
    "salons.welcomeTitle": "Tu nueva experiencia de belleza ✨",
    "salons.welcomeSubtitle": "Explora salones, guarda tus favoritos y agenda con estilistas expertos en minutos.",
    "salons.welcome1": "Descubre salones verificados",
    "salons.welcome2": "Guarda favoritos para reservar más rápido",
    "salons.welcome3": "Agenda citas con servicio, fecha y estilista",
    "salons.later": "Ver después",
    "salons.start": "Comenzar ahora",
    "salons.cityUnknown": "Ubicación no especificada",
    "salons.descriptionFallback": "Salón profesional con servicios personalizados.",
    "salons.favLabel": "Guardar favorito",
    "salons.welcomeBrand": "Bienvenido a StyleHub",
    "payments.section": "Configuración",
    "payments.title": "Agregar método de pago",
    "payments.type": "Tipo",
    "payments.card": "Tarjeta",
    "payments.paypal": "PayPal",
    "payments.transfer": "Transferencia",
    "payments.cash": "Efectivo",
    "payments.wallet": "Wallet",
    "payments.secureCardTitle": "Tarjeta segura con Stripe",
    "payments.secureCardDesc": "Aquí se capturan número, vencimiento y CVC de forma segura para guardar la tarjeta.",
    "payments.cardSaved": "Tarjeta guardada",
    "payments.cardSavedDesc": "Ya puedes recargar sin volver a capturar la tarjeta.",
    "security.loading": "Cargando seguridad de cuenta...",
    "security.email": "Correo principal",
    "security.accessMethod": "Método de acceso",
    "security.withPassword": "Correo y contraseña",
    "security.googleWithPassword": " + contraseña",
    "security.googleAccount": "Tu cuenta usa Google. Puedes añadir o actualizar contraseña para acceso tradicional.",
    "security.passwordAccount": "Tu cuenta usa registro convencional con correo y contraseña.",
    "security.changePassword": "Cambiar contraseña",
    "security.createPassword": "Crear contraseña",
    "security.currentPassword": "Contraseña actual",
    "security.newPassword": "Nueva contraseña",
    "security.confirmPassword": "Confirmar contraseña",
    "security.savePassword": "Guardando...",
    "security.updatePassword": "Actualizar contraseña",
    "security.createPasswordAction": "Crear contraseña",
    "security.dangerZone": "Zona peligrosa: eliminar cuenta",
    "security.dangerText": "Esta acción eliminará tu cuenta y datos asociados (citas, métodos y configuraciones) de forma permanente.",
    "security.confirmEmailPlaceholder": "Escribe tu correo para confirmar:",
    "security.sendDeleteToken": "Enviar token al correo",
    "security.deleteTokenHint": "Necesitas el token de 6 dígitos enviado a tu correo.",
    "security.deleteTokenPlaceholder": "Token de 6 dígitos",
    "security.deleting": "Eliminando...",
    "security.deleteForever": "Eliminar cuenta permanentemente",
    "security.badPasswordMatch": "La confirmación no coincide con la nueva contraseña.",
    "security.badPasswordTitle": "Contraseñas diferentes",
    "security.savedErrorTitle": "No se pudo guardar",
    "security.loadErrorTitle": "No se pudo cargar seguridad",
    "security.loadError": "No se pudo cargar seguridad de cuenta.",
    "security.saveError": "No se pudo actualizar la contraseña.",
    "security.savedSuccessCreated": "Contraseña creada",
    "security.savedSuccessUpdated": "Contraseña actualizada",
    "security.savedSuccessCreatedMsg": "Ya puedes iniciar sesión con correo/contraseña además de Google.",
    "security.savedSuccessUpdatedMsg": "Tu contraseña se actualizó correctamente.",
    "security.deleteConfirm": "Esta acción eliminará tu cuenta y datos asociados. ¿Deseas continuar?",
    "security.deleteSuccessTitle": "Cuenta eliminada",
    "security.deleteSuccessMsg": "Tu cuenta fue eliminada correctamente.",
    "security.deleteErrorTitle": "No se pudo eliminar",
    "security.deleteError": "No se pudo eliminar la cuenta.",
    "security.confirmEmail": "Confirma tu correo",
    "security.confirmEmailText": "Escribe tu correo exacto para enviar el token de eliminación.",
    "security.sendTokenError": "No se pudo enviar el token de eliminación.",
    "security.tokenSentTitle": "Token enviado",
    "security.tokenSentMsg": "Revisa tu correo para confirmar eliminación.",
    "security.tokenErrorTitle": "No se pudo enviar el token",
    "security.tokenError": "No se pudo enviar el token de eliminación.",
    "security.accessGoogle": "Google",
    "security.accountType": "Tu cuenta usa Google. Puedes añadir o actualizar contraseña para acceso tradicional.",
    "security.accessLabel": "Método de acceso",
    "security.accessPassword": "Correo y contraseña",
    "security.noAccountType": "Tu cuenta usa registro convencional con correo y contraseña.",
    "security.cantLoad": "Inténtalo de nuevo.",
    "security.passwordMismatch": "La confirmación no coincide con la nueva contraseña.",
    "security.passwordError": "No se pudo actualizar la contraseña.",
    "security.tokenSentButton": "Enviar token al correo",
    "security.tokenSentHint": "Necesitas el token de 6 dígitos enviado a tu correo.",
    "modal.salonProfile": "Perfil del salón",
    "modal.close": "Cerrar modal",
    "modal.defaultDescription": "Experiencia premium en belleza y cuidado personal.",
    "modal.services": "Servicios",
    "modal.stylists": "Estilistas",
    "modal.location": "Ubicación",
    "modal.noServices": "No hay servicios disponibles",
    "modal.noStylists": "No hay estilistas disponibles",
    "modal.available": "Disponible",
    "modal.unavailable": "No disponible",
    "modal.address": "Dirección",
    "modal.locationUnavailable": "La ubicación no está disponible en este momento.",
    "modal.closeButton": "Cerrar",
    "modal.bookButton": "Agendar cita",
    "modal.quickBooking": "Reserva rápida",
    "modal.bookTitle": "Agenda tu cita",
    "modal.bookSubtitle": "Completa tus datos para reservar en",
    "modal.service": "Servicio",
    "modal.selectService": "Selecciona un servicio",
    "modal.dateTime": "Fecha y hora",
    "modal.notes": "Notas (opcional)",
    "modal.bookingPlaceholder": "Detalles para tu cita",
    "modal.payment": "Forma de pago",
    "modal.cashLocal": "Efectivo en el local",
    "modal.wallet": "Saldo en tu cuenta",
    "modal.availableBalance": "Saldo disponible:",
    "modal.noBalance": "No pudimos cargar tu saldo disponible.",
    "modal.payAtSalon": "Pagarás directamente en el local al finalizar tu cita.",
    "modal.estimatedTotal": "Total estimado:",
    "modal.back": "← Volver",
    "modal.confirmBook": "Confirmar cita",
    "modal.booking": "Agendando...",
    "modal.loadError": "Error cargando detalles del salón:",
    "modal.completeBooking": "Completa tu cita",
    "modal.selectServiceDate": "Selecciona servicio y fecha/hora para continuar.",
    "modal.insufficientBalance": "Saldo insuficiente",
    "modal.insufficientBalanceText": "No tienes saldo suficiente para pagar esta cita con wallet.",
    "modal.bookSuccess": "Cita agendada",
    "modal.bookSuccessMsg": "Tu cita se registró correctamente.",
    "modal.bookFail": "No se pudo agendar",
    "onboarding.title.client": "Te damos la bienvenida a StyleHub ✨",
    "onboarding.title.business": "Bienvenido al panel de negocio ✨",
    "onboarding.subtitle.client": "En menos de un minuto te explicamos cómo funciona la app por dentro para reservar y pagar sin fricción.",
    "onboarding.subtitle.business": "Aquí controlas toda la operación de tu salón. Esta guía rápida te muestra el flujo interno de la plataforma.",
    "onboarding.header": "Bienvenida / Onboarding",
    "onboarding.skip": "Omitir",
    "onboarding.step": "Paso",
    "onboarding.of": "de",
    "onboarding.tip": "Consejo: puedes volver a consultar cada módulo desde el menú lateral del dashboard.",
    "onboarding.previous": "Anterior",
    "onboarding.next": "Siguiente",
    "onboarding.done": "Entendido, comenzar",
    "onboarding.client.step1.title": "Descubre salones",
    "onboarding.client.step1.desc": "En Salones puedes explorar negocios verificados, guardar favoritos y abrir la card de cada salón para ver servicios, estilistas y ubicación.",
    "onboarding.client.step2.title": "Agenda tu cita",
    "onboarding.client.step2.desc": "Desde la card del salón o desde Citas eliges servicio, fecha y forma de pago: efectivo en local o saldo en tu cuenta.",
    "onboarding.client.step3.title": "Wallet y pagos",
    "onboarding.client.step3.desc": "En Pagos recargas saldo, guardas tarjetas seguras con Stripe, gestionas métodos y revisas movimientos de wallet.",
    "onboarding.client.step4.title": "Controla tu cuenta",
    "onboarding.client.step4.desc": "Desde Configuración actualizas datos de perfil. Tu dashboard te muestra resumen de citas, métodos y actividad reciente.",
    "onboarding.business.step1.title": "Configura tu negocio",
    "onboarding.business.step1.desc": "En Configuración completas perfil, datos de contacto y parámetros base para operar tu salón en la plataforma.",
    "onboarding.business.step2.title": "Define tu oferta",
    "onboarding.business.step2.desc": "En Servicios defines catálogo y precios. En Estilistas gestionas tu equipo para atender citas con mejor organización.",
    "onboarding.business.step3.title": "Opera citas y sucursales",
    "onboarding.business.step3.desc": "En Citas gestionas estados y seguimiento. En Sucursales controlas expansión y visibilidad de nuevas ubicaciones.",
    "onboarding.business.step4.title": "Mide resultados",
    "onboarding.business.step4.desc": "Tu dashboard resume citas, clientes e ingresos del mes para tomar decisiones más rápido.",
    "appointments.reserve": "Reserva",
    "appointments.new": "Agendar nueva cita",
    "appointments.business": "Negocio",
    "appointments.selectBusiness": "Selecciona un negocio",
    "appointments.service": "Servicio",
    "appointments.selectService": "Selecciona un servicio",
    "appointments.stylist": "Estilista (opcional)",
    "appointments.payment": "Forma de pago",
    "appointments.cashLocal": "Efectivo en el local",
    "appointments.walletBalance": "Saldo en tu cuenta",
    "settings.title": "Preferencias del cliente",
    "settings.description": "Administra tu cuenta, seguridad y preferencias en diferentes secciones.",
    "settings.general": "General",
    "settings.general.desc": "Datos y preferencias",
    "settings.security": "Seguridad",
    "settings.security.desc": "Acceso y contraseña",
    "settings.notifications": "Notificaciones",
    "settings.notifications.desc": "Alertas y avisos",
    "settings.privacy": "Privacidad",
    "settings.privacy.desc": "Datos personales",
    "general.language": "Idioma preferido",
    "general.timezone": "Zona horaria",
    "general.language.es": "Español",
    "general.language.en": "English",
    "general.timezone.mx": "América/México (UTC-6)",
    "security.title": "Acceso y seguridad",
    "security.description": "Administra tu contraseña, métodos de acceso y opciones de eliminación de cuenta.",
    "notifications.title": "Alertas y avisos",
    "notifications.description": "Controla qué notificaciones deseas recibir sobre tus citas, pagos y actualizaciones.",
    "notifications.reminders": "Recordatorio de citas",
    "notifications.reminders.desc": "Recibe avisos 24h antes de tu cita",
    "notifications.payments": "Confirmación de pagos",
    "notifications.payments.desc": "Notificaciones de transacciones completadas",
    "notifications.promotions": "Ofertas y promociones",
    "notifications.promotions.desc": "Información sobre nuevos servicios y descuentos",
    "privacy.title": "Control de datos personales",
    "privacy.description": "Gestiona cómo se usan y comparten tus datos personales en la plataforma.",
    "privacy.profile": "Perfil público",
    "privacy.profile.desc": "Otros pueden ver tu información básica",
    "privacy.history": "Compartir historial",
    "privacy.history.desc": "Permitir que salones vean tu historial de citas",
    "privacy.analytics": "Análisis de datos",
    "privacy.analytics.desc": "Ayudarnos a mejorar con datos anónimos",
    // Business pages
    "business.services": "Servicios",
    "business.services.title": "Administrar servicios",
    "business.services.new": "Agregar nuevo servicio",
    "business.services.name": "Nombre del servicio",
    "business.services.description": "Descripción",
    "business.services.price": "Precio",
    "business.services.duration": "Duración (minutos)",
    "business.services.add": "Agregar servicio",
    "business.services.edit": "Editar servicio",
    "business.services.delete": "Eliminar servicio",
    "business.services.saving": "Guardando...",
    "business.services.deleting": "Eliminando...",
    "business.services.successAdd": "Servicio agregado",
    "business.services.successEdit": "Servicio actualizado",
    "business.services.successDelete": "Servicio eliminado",
    "business.services.errorAdd": "No se pudo agregar el servicio",
    "business.services.errorEdit": "No se pudo actualizar el servicio",
    "business.services.errorDelete": "No se pudo eliminar el servicio",
    "business.services.noServices": "Sin servicios aún",
    "business.stylists": "Estilistas",
    "business.stylists.title": "Administrar estilistas",
    "business.stylists.new": "Agregar nuevo estilista",
    "business.stylists.name": "Nombre completo",
    "business.stylists.specialization": "Especialización",
    "business.stylists.phone": "Número de teléfono",
    "business.stylists.add": "Agregar estilista",
    "business.stylists.edit": "Editar estilista",
    "business.stylists.delete": "Eliminar estilista",
    "business.stylists.saving": "Guardando...",
    "business.stylists.deleting": "Eliminando...",
    "business.stylists.successAdd": "Estilista agregado",
    "business.stylists.successEdit": "Estilista actualizado",
    "business.stylists.successDelete": "Estilista eliminado",
    "business.stylists.errorAdd": "No se pudo agregar el estilista",
    "business.stylists.errorEdit": "No se pudo actualizar el estilista",
    "business.stylists.errorDelete": "No se pudo eliminar el estilista",
    "business.stylists.noStylists": "Sin estilistas aún",
    "business.branches": "Sucursales",
    "business.branches.title": "Administrar sucursales",
    "business.branches.new": "Agregar nueva sucursal",
    "business.branches.name": "Nombre de sucursal",
    "business.branches.address": "Dirección",
    "business.branches.city": "Ciudad",
    "business.branches.state": "Estado",
    "business.branches.country": "País",
    "business.branches.phone": "Teléfono",
    "business.branches.add": "Agregar sucursal",
    "business.branches.edit": "Editar sucursal",
    "business.branches.delete": "Eliminar sucursal",
    "business.branches.saving": "Guardando...",
    "business.branches.deleting": "Eliminando...",
    "business.branches.successAdd": "Sucursal agregada",
    "business.branches.successEdit": "Sucursal actualizada",
    "business.branches.successDelete": "Sucursal eliminada",
    "business.branches.errorAdd": "No se pudo agregar la sucursal",
    "business.branches.errorEdit": "No se pudo actualizar la sucursal",
    "business.branches.errorDelete": "No se pudo eliminar la sucursal",
    "business.branches.noBranches": "Sin sucursales aún",
    "business.appointments": "Citas",
    "business.appointments.title": "Administrar citas",
    "business.appointments.new": "Nueva cita",
    "business.appointments.client": "Cliente",
    "business.appointments.service": "Servicio",
    "business.appointments.stylist": "Estilista",
    "business.appointments.dateTime": "Fecha y hora",
    "business.appointments.status": "Estado",
    "business.appointments.confirm": "Confirmar",
    "business.appointments.complete": "Completar",
    "business.appointments.cancel": "Cancelar",
    "business.appointments.noAppointments": "Sin citas",
    "business.appointments.loading": "Cargando citas...",
  },
  en: {
    "app.brand": "STYLEHUB",
    "app.subtitle.client": "My account",
    "app.subtitle.business": "Business panel",
    "nav.dashboard": "Dashboard",
    "nav.dashboard.client": "Overview",
    "nav.dashboard.business": "Overview",
    "nav.salons": "Salons",
    "nav.appointments": "My appointments",
    "nav.payments": "Payments",
    "nav.settings": "Settings",
    "nav.branches": "Branches",
    "nav.services": "Services",
    "nav.stylists": "Stylists",
    "nav.profile": "Profile",
    "nav.home": "Home",
    "nav.logout": "Logout",
    "tip.client.title": "Tip",
    "tip.client.body": "Book in advance and save a card for quick checkout.",
    "tip.business.title": "Business tip",
    "tip.business.body": "Keep your services and stylists updated to convert more bookings.",
    "dashboard.client.welcome": "Welcome back! 👋",
    "dashboard.client.subtitle": "Here’s a summary of your activity and upcoming appointments.",
    "dashboard.client.totalAppointments": "Total appointments",
    "dashboard.client.pending": "Pending",
    "dashboard.client.confirmed": "Confirmed",
    "dashboard.client.methods": "Methods",
    "dashboard.client.spent": "Spent",
    "dashboard.client.upcoming": "Upcoming appointments",
    "dashboard.client.agenda": "Your agenda",
    "dashboard.client.activity": "Activity",
    "dashboard.client.latest": "Latest bookings",
    "dashboard.client.activeMethod": "Active method",
    "dashboard.client.fastPay": "Fast checkout",
    "dashboard.client.savedMethods": "Saved methods",
    "dashboard.client.methodsActive": "You have active payment options.",
    "dashboard.client.steps": "Next steps",
    "dashboard.client.step1": "Book your first appointment",
    "dashboard.client.step2": "Save a payment method",
    "dashboard.client.step3": "Receive email confirmations",
    "dashboard.client.noUpcoming": "No upcoming appointments",
    "dashboard.client.noUpcomingDesc": "Book an appointment to see your calendar.",
    "dashboard.client.methodType": "Type",
    "dashboard.client.noMethod": "No method configured",
    "dashboard.client.noMethodDesc": "Add a method for faster checkout.",
    "dashboard.business.title": "Full control of your salon",
    "dashboard.business.subtitle": "Manage services, team, and appointments from one place.",
    "dashboard.business.quickActions": "Quick actions",
    "dashboard.business.manageServices": "Manage services",
    "dashboard.business.manageStylists": "Manage stylists",
    "dashboard.business.reviewAppointments": "Review appointments",
    "dashboard.business.manageBranches": "Manage branches",
    "dashboard.business.configureSalon": "Configure salon",
    "dashboard.business.monthlyPerformance": "Monthly performance",
    "dashboard.business.revenue": "Confirmed revenue from completed services this month.",
    "dashboard.business.services": "Services",
    "dashboard.business.stylists": "Stylists",
    "dashboard.business.branches": "Branches",
    "dashboard.business.upcoming": "Upcoming appointments",
    "dashboard.business.clients": "Clients",
    "dashboard.business.revenueMonth": "Monthly revenue",
    "dashboard.business.summary": "Business Dashboard",
    "dashboard.business.control": "Manage services, team, and appointments from one place.",
    "salons.badge": "Premium Beauty Network",
    "salons.title": "Discover our salons 💇",
    "salons.subtitle": "Explore verified salons, compare services, and book with expert stylists in seconds.",
    "salons.available": "salons available",
    "salons.favorites": "Your favorites ❤️",
    "salons.saved": "saved",
    "salons.noAvailable": "No salons available",
    "salons.noAvailableDesc": "Come back later to see new booking options.",
    "salons.verified": "Verified",
    "salons.viewServices": "View services",
    "salons.welcomeTitle": "Your new beauty experience ✨",
    "salons.welcomeSubtitle": "Explore salons, save your favorites, and book with expert stylists in minutes.",
    "salons.welcome1": "Discover verified salons",
    "salons.welcome2": "Save favorites for faster booking",
    "salons.welcome3": "Book appointments by service, date, and stylist",
    "salons.later": "Later",
    "salons.start": "Start now",
    "salons.cityUnknown": "Location not specified",
    "salons.descriptionFallback": "Professional salon with personalized services.",
    "salons.favLabel": "Save favorite",
    "salons.welcomeBrand": "Welcome to StyleHub",
    "security.loading": "Loading account security...",
    "security.email": "Primary email",
    "security.accessMethod": "Access method",
    "security.withPassword": "Email and password",
    "security.googleWithPassword": " + password",
    "security.googleAccount": "Your account uses Google. You can add or update a password for traditional access.",
    "security.passwordAccount": "Your account uses the conventional email/password sign-in.",
    "security.changePassword": "Change password",
    "security.createPassword": "Create password",
    "security.currentPassword": "Current password",
    "security.newPassword": "New password",
    "security.confirmPassword": "Confirm password",
    "security.savePassword": "Saving...",
    "security.updatePassword": "Update password",
    "security.createPasswordAction": "Create password",
    "security.dangerZone": "Danger zone: delete account",
    "security.dangerText": "This action permanently removes your account and associated data (appointments, methods, and settings).",
    "security.confirmEmailPlaceholder": "Type your email to confirm:",
    "security.sendDeleteToken": "Send token to email",
    "security.deleteTokenHint": "You need the 6-digit token sent to your email.",
    "security.deleteTokenPlaceholder": "6-digit token",
    "security.deleting": "Deleting...",
    "security.deleteForever": "Delete account permanently",
    "security.badPasswordMatch": "The confirmation does not match the new password.",
    "security.badPasswordTitle": "Different passwords",
    "security.savedErrorTitle": "Could not save",
    "security.loadErrorTitle": "Could not load security",
    "security.loadError": "Could not load account security.",
    "security.saveError": "Could not update the password.",
    "security.savedSuccessCreated": "Password created",
    "security.savedSuccessUpdated": "Password updated",
    "security.savedSuccessCreatedMsg": "You can now sign in with email/password in addition to Google.",
    "security.savedSuccessUpdatedMsg": "Your password was updated successfully.",
    "security.deleteConfirm": "This action will delete your account and associated data. Continue?",
    "security.deleteSuccessTitle": "Account deleted",
    "security.deleteSuccessMsg": "Your account was deleted successfully.",
    "security.deleteErrorTitle": "Could not delete",
    "security.deleteError": "Could not delete the account.",
    "security.confirmEmail": "Confirm your email",
    "security.confirmEmailText": "Type your exact email to send the deletion token.",
    "security.sendTokenError": "Could not send deletion token.",
    "security.tokenSentTitle": "Token sent",
    "security.tokenSentMsg": "Check your email to confirm deletion.",
    "security.tokenErrorTitle": "Could not send token",
    "security.tokenError": "Could not send the deletion token.",
    "security.accessGoogle": "Google",
    "security.accountType": "Your account uses Google. You can add or update a password for traditional access.",
    "security.accessLabel": "Access method",
    "security.accessPassword": "Email and password",
    "security.noAccountType": "Your account uses conventional email and password sign-in.",
    "security.cantLoad": "Try again.",
    "security.passwordMismatch": "The confirmation does not match the new password.",
    "security.passwordError": "Could not update the password.",
    "security.tokenSentButton": "Send token to email",
    "security.tokenSentHint": "You need the 6-digit token sent to your email.",
    "modal.salonProfile": "Salon profile",
    "modal.close": "Close modal",
    "modal.defaultDescription": "Premium beauty and personal care experience.",
    "modal.services": "Services",
    "modal.stylists": "Stylists",
    "modal.location": "Location",
    "modal.noServices": "No services available",
    "modal.noStylists": "No stylists available",
    "modal.available": "Available",
    "modal.unavailable": "Unavailable",
    "modal.address": "Address",
    "modal.locationUnavailable": "Location is not available right now.",
    "modal.closeButton": "Close",
    "modal.bookButton": "Book appointment",
    "modal.quickBooking": "Quick booking",
    "modal.bookTitle": "Book your appointment",
    "modal.bookSubtitle": "Complete your details to book at",
    "modal.service": "Service",
    "modal.selectService": "Select a service",
    "modal.dateTime": "Date and time",
    "modal.notes": "Notes (optional)",
    "modal.bookingPlaceholder": "Appointment details",
    "modal.payment": "Payment method",
    "modal.cashLocal": "Cash at the salon",
    "modal.wallet": "Wallet balance",
    "modal.availableBalance": "Available balance:",
    "modal.noBalance": "We couldn't load your available balance.",
    "modal.payAtSalon": "You will pay directly at the salon when the appointment ends.",
    "modal.estimatedTotal": "Estimated total:",
    "modal.back": "← Back",
    "modal.confirmBook": "Confirm appointment",
    "modal.booking": "Booking...",
    "modal.loadError": "Error loading salon details:",
    "modal.completeBooking": "Complete your appointment",
    "modal.selectServiceDate": "Select service and date/time to continue.",
    "modal.insufficientBalance": "Insufficient balance",
    "modal.insufficientBalanceText": "You don't have enough wallet balance to pay for this appointment.",
    "modal.bookSuccess": "Appointment booked",
    "modal.bookSuccessMsg": "Your appointment was registered successfully.",
    "modal.bookFail": "Could not book",
    "onboarding.title.client": "Welcome to StyleHub ✨",
    "onboarding.title.business": "Welcome to the business panel ✨",
    "onboarding.subtitle.client": "In less than a minute we explain how the app works so you can book and pay smoothly.",
    "onboarding.subtitle.business": "Here you control your entire salon operation. This quick guide shows the platform flow.",
    "onboarding.header": "Welcome / Onboarding",
    "onboarding.skip": "Skip",
    "onboarding.step": "Step",
    "onboarding.of": "of",
    "onboarding.tip": "Tip: you can revisit each module from the sidebar dashboard menu.",
    "onboarding.previous": "Previous",
    "onboarding.next": "Next",
    "onboarding.done": "Got it, let's start",
    "onboarding.client.step1.title": "Discover salons",
    "onboarding.client.step1.desc": "In Salons you can explore verified businesses, save favorites, and open each salon card to see services, stylists, and location.",
    "onboarding.client.step2.title": "Book your appointment",
    "onboarding.client.step2.desc": "From the salon card or from Appointments you choose service, date, and payment method: cash at the salon or wallet balance.",
    "onboarding.client.step3.title": "Wallet and payments",
    "onboarding.client.step3.desc": "In Payments you top up balance, save secure cards with Stripe, manage methods, and review wallet transactions.",
    "onboarding.client.step4.title": "Manage your account",
    "onboarding.client.step4.desc": "From Settings you update profile data. Your dashboard shows appointment summary, methods, and recent activity.",
    "onboarding.business.step1.title": "Set up your business",
    "onboarding.business.step1.desc": "In Settings you complete profile, contact data, and base parameters to operate your salon on the platform.",
    "onboarding.business.step2.title": "Define your offer",
    "onboarding.business.step2.desc": "In Services you define your catalog and prices. In Stylists you manage your team to handle appointments better.",
    "onboarding.business.step3.title": "Run appointments and branches",
    "onboarding.business.step3.desc": "In Appointments you manage statuses and follow-up. In Branches you control expansion and visibility of new locations.",
    "onboarding.business.step4.title": "Measure results",
    "onboarding.business.step4.desc": "Your dashboard summarizes appointments, clients, and monthly revenue so you can make decisions faster.",
    "appointments.reserve": "Booking",
    "appointments.new": "Book a new appointment",
    "settings.title": "Client Preferences",
    "settings.description": "Manage your account, security, and preferences in different sections.",
    "settings.general": "General",
    "settings.general.desc": "Data and preferences",
    "settings.security": "Security",
    "settings.security.desc": "Access and password",
    "settings.notifications": "Notifications",
    "settings.notifications.desc": "Alerts and announcements",
    "settings.privacy": "Privacy",
    "settings.privacy.desc": "Personal data",
    "general.language": "Preferred language",
    "general.timezone": "Timezone",
    "general.language.es": "Español",
    "general.language.en": "English",
    "general.timezone.mx": "America/Mexico (UTC-6)",
    "security.title": "Access and Security",
    "security.description": "Manage your password, access methods, and account deletion options.",
    "notifications.title": "Alerts and Announcements",
    "notifications.description": "Control what notifications you receive about your appointments, payments, and updates.",
    "notifications.reminders": "Appointment Reminder",
    "notifications.reminders.desc": "Get alerts 24h before your appointment",
    "notifications.payments": "Payment Confirmation",
    "notifications.payments.desc": "Notifications of completed transactions",
    "notifications.promotions": "Offers and Promotions",
    "notifications.promotions.desc": "Information about new services and discounts",
    "privacy.title": "Personal Data Control",
    "privacy.description": "Manage how your personal data is used and shared on the platform.",
    "privacy.profile": "Public Profile",
    "privacy.profile.desc": "Others can see your basic information",
    "privacy.history": "Share History",
    "privacy.history.desc": "Allow salons to see your appointment history",
    "privacy.analytics": "Data Analytics",
    "privacy.analytics.desc": "Help us improve with anonymous data",
    // Payments page
    "payments.title": "Add payment method",
    "payments.addMethod": "Add payment method",
    "payments.type": "Type",
    "payments.card": "Card",
    "payments.paypal": "PayPal",
    "payments.transfer": "Bank transfer",
    "payments.cash": "Cash",
    "payments.wallet": "Wallet",
    "payments.cardLabel": "Secure card with Stripe",
    "payments.cardDesc": "Number, expiration, and CVC are captured securely to save the card.",
    "payments.holderName": "Cardholder name",
    "payments.optional": "(optional)",
    "payments.cardNumber": "Card number",
    "payments.useLink": "Use link",
    "payments.makeDefault": "Mark as default payment method",
    "payments.saveCard": "Save secure card",
    "payments.wallet.title": "Balance and recharges",
    "payments.wallet.current": "Current balance:",
    "payments.wallet.recharge": "Amount to recharge (min. $10)",
    "payments.wallet.selectMethod": "Select new card - Open Stripe Checkout",
    "payments.wallet.stripe": "Stripe Checkout instruction text",
    "payments.wallet.openStripe": "Open Stripe Checkout",
    "payments.wallet.methods": "Your methods",
    "payments.errorLoad": "Could not load payment methods",
    "payments.errorLoadRetry": "Try again.",
    "payments.successAdd": "Payment method added",
    "payments.successAdd.desc": "Your method is now available for checkout.",
    "payments.successDelete": "Method removed",
    "payments.successDelete.desc": "The payment method was deleted.",
    "payments.successSetDefault": "Default method updated",
    "payments.successSetDefault.desc": "Your checkout will use this method by default.",
    "payments.successRecharge": "Recharge confirmed",
    "payments.successRecharge.desc": "Your wallet has been credited.",
    "payments.errorAdd": "Could not add method",
    "payments.errorDelete": "Could not delete method",
    "payments.errorSetDefault": "Could not update default",
    "payments.errorRecharge": "Recharge pending confirmation",
    "payments.errorRecharge.desc": "Stripe has not confirmed payment yet.",
    // Appointments page
    "appointments.title": "My appointments",
    "appointments.newAppointment": "Schedule new appointment",
    "appointments.business": "Business",
    "appointments.selectBusiness": "Select a business",
    "appointments.service": "Service",
    "appointments.selectService": "Select a service",
    "appointments.stylist": "Stylist (optional)",
    "appointments.selectStylist": "Select a stylist",
    "appointments.dateTime": "Date and time",
    "appointments.selectDateTime": "Select date and time",
    "appointments.notes": "Notes (optional)",
    "appointments.notesPlaceholder": "Any details for your appointment",
    "appointments.payment": "Payment method",
    "appointments.cashLocal": "Cash at salon",
    "appointments.walletBalance": "Wallet balance",
    "appointments.schedule": "Schedule appointment",
    "appointments.scheduling": "Scheduling...",
    "appointments.history": "Appointment history",
    "appointments.upcoming": "Upcoming",
    "appointments.past": "Past",
    "appointments.status": "Status",
    "appointments.pending": "Pending",
    "appointments.confirmed": "Confirmed",
    "appointments.completed": "Completed",
    "appointments.cancelled": "Cancelled",
    "appointments.actions": "Actions",
    "appointments.reschedule": "Reschedule",
    "appointments.cancel": "Cancel",
    "appointments.delete": "Delete",
    "appointments.clearHistory": "Clear history",
    "appointments.clearPastOnly": "Clear past appointments only",
    "appointments.clearAll": "Delete all appointments",
    "appointments.rescheduling": "Rescheduling...",
    "appointments.cancelling": "Cancelling...",
    "appointments.deleting": "Deleting...",
    "appointments.clearing": "Clearing...",
    "appointments.successSchedule": "Appointment scheduled",
    "appointments.successSchedule.desc": "Your appointment was registered successfully.",
    "appointments.successReschedule": "Appointment rescheduled",
    "appointments.successReschedule.desc": "Your new date and time have been saved.",
    "appointments.successCancel": "Appointment cancelled",
    "appointments.successCancel.desc": "The appointment was cancelled.",
    "appointments.successDelete": "Appointment deleted",
    "appointments.successDelete.desc": "The appointment was removed from your history.",
    "appointments.successClear": "History cleared",
    "appointments.successClear.desc": "Your appointment history has been cleaned.",
    "appointments.errorSchedule": "Could not schedule appointment",
    "appointments.errorReschedule": "Could not reschedule appointment",
    "appointments.errorCancel": "Could not cancel appointment",
    "appointments.errorDelete": "Could not delete appointment",
    "appointments.errorClear": "Could not clear history",
    "appointments.sameDayError": "Cannot reschedule to the same day",
    "appointments.noAppointments": "No appointments yet",
    "appointments.noAppointmentsDesc": "Schedule your first appointment to get started.",
    // Business pages
    "business.services": "Services",
    "business.services.title": "Manage services",
    "business.services.new": "Add new service",
    "business.services.name": "Service name",
    "business.services.description": "Description",
    "business.services.price": "Price",
    "business.services.duration": "Duration (minutes)",
    "business.services.add": "Add service",
    "business.services.edit": "Edit service",
    "business.services.delete": "Delete service",
    "business.services.saving": "Saving...",
    "business.services.deleting": "Deleting...",
    "business.services.successAdd": "Service added",
    "business.services.successEdit": "Service updated",
    "business.services.successDelete": "Service deleted",
    "business.services.errorAdd": "Could not add service",
    "business.services.errorEdit": "Could not update service",
    "business.services.errorDelete": "Could not delete service",
    "business.services.noServices": "No services yet",
    "business.stylists": "Stylists",
    "business.stylists.title": "Manage stylists",
    "business.stylists.new": "Add new stylist",
    "business.stylists.name": "Full name",
    "business.stylists.specialization": "Specialization",
    "business.stylists.phone": "Phone number",
    "business.stylists.add": "Add stylist",
    "business.stylists.edit": "Edit stylist",
    "business.stylists.delete": "Delete stylist",
    "business.stylists.saving": "Saving...",
    "business.stylists.deleting": "Deleting...",
    "business.stylists.successAdd": "Stylist added",
    "business.stylists.successEdit": "Stylist updated",
    "business.stylists.successDelete": "Stylist deleted",
    "business.stylists.errorAdd": "Could not add stylist",
    "business.stylists.errorEdit": "Could not update stylist",
    "business.stylists.errorDelete": "Could not delete stylist",
    "business.stylists.noStylists": "No stylists yet",
    "business.branches": "Branches",
    "business.branches.title": "Manage branches",
    "business.branches.new": "Add new branch",
    "business.branches.name": "Branch name",
    "business.branches.address": "Address",
    "business.branches.city": "City",
    "business.branches.state": "State",
    "business.branches.country": "Country",
    "business.branches.phone": "Phone",
    "business.branches.add": "Add branch",
    "business.branches.edit": "Edit branch",
    "business.branches.delete": "Delete branch",
    "business.branches.saving": "Saving...",
    "business.branches.deleting": "Deleting...",
    "business.branches.successAdd": "Branch added",
    "business.branches.successEdit": "Branch updated",
    "business.branches.successDelete": "Branch deleted",
    "business.branches.errorAdd": "Could not add branch",
    "business.branches.errorEdit": "Could not update branch",
    "business.branches.errorDelete": "Could not delete branch",
    "business.branches.noBranches": "No branches yet",
    "business.appointments": "Appointments",
    "business.appointments.title": "Manage appointments",
    "business.appointments.new": "New appointment",
    "business.appointments.client": "Client",
    "business.appointments.service": "Service",
    "business.appointments.stylist": "Stylist",
    "business.appointments.dateTime": "Date and time",
    "business.appointments.status": "Status",
    "business.appointments.confirm": "Confirm",
    "business.appointments.complete": "Complete",
    "business.appointments.cancel": "Cancel",
    "business.appointments.noAppointments": "No appointments",
    "business.appointments.loading": "Loading appointments...",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("es");

  useEffect(() => {
    // Cargar idioma guardado del localStorage
    const saved = localStorage.getItem("language") as Language | null;
    if (saved && (saved === "es" || saved === "en")) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage debe ser usado dentro de LanguageProvider");
  }
  return context;
}
